[package]
name = "play-wt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36", features = ["full"] }
wtransport = "0.1.10"
thiserror = "1.0"
data-encoding = "2.5.0"